config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq)

  root 'dashboard#index'

  get 'up' => 'rails/health#show'

  devise_for :users,
             path: '/', only: %i[sessions passwords registrations omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords', registrations: 'registrations' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :embed do
    post 'forms', to: 'embeds#forms_create'

    resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
      resources :values, only: %i[index], controller: 'submit_form_values'
    end

    resources :submitters, only: %i[], param: 'slug' do
      resources :download, only: %i[index], controller: 'submissions_download'
    end

    get 'fonts/DancingScript-Regular.otf', to: 'fonts#dancing_script_regular'

    namespace :api do
      post 'submitter_form_views', to: 'submitter_form_views#create'
      post 'attachments', to: 'attachments#create'
    end

    post 'send_submission_email', to: 'submissions#send_email', defaults: { format: :json }
  end

  mount Rswag::Ui::Engine => '/docs/api'
  mount Rswag::Api::Engine => '/docs/api'

  namespace :api, defaults: { format: :json } do
    get 'submissions/:slug/download', to: 'submissions_download#download'
    resources :attachments, only: %i[create]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      collection do
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create]
  resources :user_configs, only: %i[create]
  resources :encrypted_user_configs, only: %i[destroy]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :users, only: %i[new create edit update destroy]
  resource :user_signature, only: %i[edit update destroy]
  resource :user_initials, only: %i[edit update destroy]
  resources :submissions_archived, only: %i[index], path: 'submissions/archived'
  resources :submissions, only: %i[index], controller: 'submissions_dashboard'
  resources :submissions, only: %i[show destroy]
  # resources :console_redirect, only: %i[index]
  resources :upgrade, only: %i[index], controller: 'console_redirect'
  resources :manage, only: %i[index], controller: 'console_redirect'
  resource :testing_account, only: %i[show destroy]
  resources :testing_api_settings, only: %i[index]
  resources :submitters_autocomplete, only: %i[index]
  resources :template_folders_autocomplete, only: %i[index]
  resources :webhook_preferences, only: %i[create]
  resource :templates_upload, only: %i[create]
  authenticated do
    resource :templates_upload, only: %i[show], path: 'new'
  end
  resources :templates_archived, only: %i[index], path: 'templates/archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :template_sharings_testing, only: %i[create]
  resources :templates, only: %i[index], controller: 'templates_dashboard'
  resources :templates, only: %i[new create edit update show destroy] do
    resources :documents, only: %i[create], controller: 'template_documents'
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resource :preview, only: %i[show], controller: 'templates_preview'
    resource :code_modal, only: %i[show], controller: 'templates_code_modal'
    resource :preferences, only: %i[show create], controller: 'templates_preferences'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:signed_uuid'
  resource :blobs_proxy, only: %i[show], path: '/file/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'
  resource :blobs_proxy, only: %i[show], path: '/blobs_proxy/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resources :submit_form, only: %i[], path: '' do
    get :success, on: :collection
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    resources :values, only: %i[index], controller: 'submit_form_values'
    get :completed
  end

  resources :submit_form_draw_signature, only: %i[show], path: 'p', param: 'slug'

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug' do
    get :completed
  end

  resources :send_submission_email, only: %i[create] do
    get :success, on: :collection
  end

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    # resources :storage, only: %i[index create], controller: 'storage_settings'
    # resources :email, only: %i[index create], controller: 'email_smtp_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resources :archived_users, only: %i[index], path: 'users/:status', controller: 'users',
                               defaults: { status: :archived }
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    resources :api, only: %i[index create], controller: 'api_settings'
    resource :account, only: %i[show update destroy]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  ActiveSupport.run_load_hooks(:routes, self)
end

app/views/shared/_attribution.html.erb
<%= render 'shared/powered_by', with_counter: local_assigns[:with_counter], link_path: local_assigns[:link_path] %>

app/views/shared/_classes.html.erb
<% 'stats stat stat-figure stat-title stat-value text-accent' %>

app/views/shared/_clipboard_copy.html.erb
<clipboard-copy data-text="<%= text %>">
  <label class="<%= local_assigns[:class] %>">
    <input type="radio" class="peer hidden">
    <span class="peer-checked:hidden flex items-center space-x-2">
      <%= svg_icon(local_assigns[:icon] || 'link', class: local_assigns[:icon_class] || 'w-6 h-6 text-white') %>
      <span class="hidden md:inline">
        <%= local_assigns[:copy_title] || 'Copy' %>
      </span>
      <% if local_assigns[:copy_title_md] %>
        <span class="inline md:hidden">
          <%= local_assigns[:copy_title_md] %>
        </span>
      <% end %>
    </span>
    <span class="hidden peer-checked:flex items-center space-x-2">
      <%= svg_icon(local_assigns[:copied_icon] || 'clipboard_copy', class: local_assigns[:icon_class] || 'w-6 h-6 text-white') %>
      <span class="hidden md:inline">
        <%= local_assigns[:copied_title] || 'Copied' %>
      </span>
      <% if local_assigns[:copied_title_md] %>
        <span class="inline md:hidden">
          <%= local_assigns[:copied_title_md] %>
        </span>
      <% end %>
    </span>
  </label>
</clipboard-copy>

app/views/shared/_email_attribution.html.erb
<p>
  ---
</p>
<p>
  Sent using <a href="<%= Uvtsign::PRODUCT_URL %>/"><%= Uvtsign.product_name %></a>
</p>

app/views/shared/_field_error.html.erb
<% 'input-error' %>
<span class="label-text-alt text-red-400 mt-1">
  <%= message %>
</span>

app/views/shared/_mailer_attribution.html.erb
<%= render 'shared/email_attribution' %>

app/views/shared/_meta.html.erb
<% title = content_for(:html_title) || 'UVTSign' %>
<meta property="og:title" content="<%= title %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= root_url %>">
<meta property="og:site_name" content="UVTSign">
<% unless content_for(:disable_image_preview) %>
  <meta property="og:image" content="<%= image_pack_url('images/preview.png') %>">
  <meta property="og:image:width" content="800">
  <meta property="og:image:height" content="800">
<% end %>
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">


<link rel="icon" type="image/png" sizes="64x64" href="/favicon.ico">
<meta name="theme-color" content="#faf7f5">

app/views/shared/_navbar.html.erb
<div class="max-w-6xl mb-4 mx-auto px-4 md:px-2 py-3 flex items-center justify-between">
  <div class="flex items-center space-x-4">
    <a href="<%= root_path %>" class="text-2xl font-bold items-center flex space-x-2">
      <%= render 'shared/title' %>
    </a>
  </div>
  <% if signed_in? %>
    <div class="space-x-4 flex items-center">
        <div class="flex items-center justify-center space-x-4 mr-1">
          <%= link_to 'Settings', settings_profile_index_path, class: 'hidden md:inline-flex font-medium text-lg' %>
        </div>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="cursor-pointer bg-base-content text-purple-300 rounded-full p-2 w-9 justify-center flex">
          <span class="text-sm align-text-top"><%= current_user.initials %></span>
        </label>
        <ul tabindex="0" class="z-10 dropdown-content p-2 mt-2 shadow menu text-base bg-base-100 rounded-box w-40 text-right">
          <li>
            <%= link_to settings_profile_index_path, class: 'flex items-center' do %>
              <%= svg_icon('adjustments', class: 'w-5 h-5 flex-shrink-0 stroke-2') %>
              <span class="mr-1">Profile</span>
            <% end %>
          </li>

          <% if can?(:read, EncryptedConfig.new(key: EncryptedConfig::ESIGN_CERTS_KEY, account: current_account)) %>
            <li>
              <%= link_to settings_esign_path, class: 'flex items-center' do %>
                <%= svg_icon('zoom_check', class: 'w-5 h-5 stroke-2') %>
                <span class="mr-1">Verify PDF</span>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'flex items-center' do %>
              <%= svg_icon('logout', class: 'w-5 h-5 stroke-2 mr-2 inline') %>
              <span class="mr-1">Sign out</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="flex space-x-2">
      <% if request.path != new_user_session_path %>
        <%= link_to new_user_session_path({ lang: params[:lang] }.compact_blank), class: 'font-medium text-lg' do %>
          <span class="flex items-center justify-center space-x-1">
            <%= svg_icon('login', class: 'w-6 h-6') %>
            <span><%= t('sign_in') %></span>
          </span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_pagination.html.erb
<% link = pagy_anchor(@pagy) %>
<% if @pagy.pages > 1 %>
  <div class="flex my-6 justify-center md:justify-between">
    <div class="hidden md:block text-sm">
      <%= @pagy.from %>-<%= local_assigns.fetch(:to, @pagy.to) %> of <%= local_assigns.fetch(:count, @pagy.count) %> <%= local_assigns[:items_name] || 'items' %>
      <%= local_assigns[:left_additional_html] %>
    </div>
    <div class="join">
      <% if @pagy.prev %>
        <%== link.call(@pagy.prev, '«', classes: 'join-item btn min-h-full h-10') %>
      <% else %>
        <span class="join-item btn btn-disabled !bg-base-200 min-h-full h-10">«</span>
      <% end %>
      <span class="join-item btn uppercase min-h-full h-10">
        Page <%= @pagy.page %>
      </span>
      <% if @pagy.next %>
        <%== link.call(@pagy.next, '»', classes: 'join-item btn min-h-full h-10') %>
      <% else %>
        <span class="join-item btn btn-disabled !bg-base-200 min-h-full h-10">»</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_powered_by.html.erb
<div class="text-center px-2">
  <% if local_assigns[:with_counter] %>
    <% count = Submitter.where.not(completed_at: nil).distinct.count(:submission_id) %>
    <% if count > 1 %>
      <b><%= count %></b> documents signed with
    <% else %>
      Powered by
    <% end %>
  <% else %>
    Powered by
  <% end %>
  <a href="<%= Uvtsign::PRODUCT_URL %><%= local_assigns[:link_path] %>" class="underline"><%= Uvtsign.product_name %></a>
</div>

app/views/shared/_search_input.html.erb
<form action="<%= url_for %>" method="get" class="items-center hidden md:flex">
  <% if params[:status].present? %>
    <input name="status" value="<%= params[:status] %>" class="hidden">
  <% end %>
  <% if params[:q].present? %>
    <div class="relative">
      <a href="<%= url_for(params.to_unsafe_h.except(:q)) %>" title="Clear" class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-auto text-neutral text-2xl font-extralight">
        &times;
      </a>
    </div>
  <% end %>
  <input id="search" name="q" value="<%= params[:q] %>" class="input input-ghost text-lg pr-10 -mr-12 <%= 'pl-8 input-outlined' if params[:q].present? %>" placeholder="<%= local_assigns[:placeholder] %>">
  <button type="submit" title="Search" class="btn btn-ghost btn-circle" onclick="window.search.value || document.activeElement === window.search ? null : [event.preventDefault(), window.search.focus()]">
    <span class="enabled">
      <%= svg_icon('search', class: 'w-6 h-6 stroke-2') %>
    </span>
    <span class="disabled">
      <%= svg_icon('loader', class: 'w-5 h-5 animate-spin') %>
    </span>
  </button>
</form>

app/views/shared/_title.html.erb
<%= render 'shared/logo' %>
<span>UVTSign</span>

app/views/shared/_turbo_drawer.html.erb
<turbo-frame id="drawer">
  <turbo-modal class="modal modal-open items-start !animate-none justify-end overflow-y-auto !justify-normal md:!justify-end" data-close-after-submit="<%= local_assigns.key?(:close_after_submit) ? local_assigns[:close_after_submit] : true %>">
    <div class="absolute top-0 bottom-0 right-0 left-0" data-action="click:turbo-modal#close"></div>
    <div class="bg-base-100 min-h-screen max-h-screen relative w-full relative overflow-y-auto">
      <% if local_assigns[:title] %>
        <div class="flex justify-between bg-base-100 py-2 px-4 items-center border-b pb-2 font-medium">
          <span>
            <%= local_assigns[:title] %>
          </span>
          <a href="#" class="text-xl" data-action="click:turbo-modal#close">&times;</a>
        </div>
      <% else %>
        <span data-action="click:turbo-modal#close" class="absolute btn border border-base-100 bg-base-100 hover:bg-base-300 hover:border-base-300 btn-primary !text-base btn-sm btn-circle" style="left: -40px; top: 6px">
          &times;
        </span>
      <% end %>
      <div class="w-full md:w-[620px] overflow-y-auto" style="max-height: calc(100vh - <%= local_assigns[:title] ? '45px' : '0px' %>)">
        <%= yield %>
      </div>
    </div>
  </turbo-modal>
</turbo-frame>

app/views/shared/_turbo_modal_large.html.erb
<turbo-frame id="modal">
  <turbo-modal class="modal modal-open items-start !animate-none overflow-y-auto !justify-normal md:!justify-center" data-close-after-submit="<%= local_assigns.key?(:close_after_submit) ? local_assigns[:close_after_submit] : true %>">
    <div class="absolute top-0 bottom-0 right-0 left-0" data-action="click:turbo-modal#close"></div>
    <div class="bg-base-100 min-h-screen max-h-screen md:min-h-fit md:mt-3 md:rounded-2xl relative w-full relative overflow-y-auto">
      <% if local_assigns[:title] %>
        <div class="flex justify-between bg-base-100 py-2 px-5 items-center border-b pb-2 font-medium mt-0.5">
          <span>
            <%= local_assigns[:title] %>
          </span>
          <a href="#" class="text-xl" data-action="click:turbo-modal#close">&times;</a>
        </div>
      <% end %>
      <div class="w-full md:w-[590px] overflow-y-auto" style="max-height: calc(100vh - 14px - 45px)">
        <%= yield %>
      </div>
    </div>
  </turbo-modal>
</turbo-frame>